spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Database_Name
    username: your username
    password: your password

  jpa:
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /api/v1.0

aws:
  access:
    key: your_access_key
  secret:
    key: your_secret_key
  region: ap-south-1
  bucket:
    name: your_bucket_name

jwt:
  secret:
    key: thisismysecretkeyfortheupcomingproject

razorpay:
  key:
    id: your id
    secret: your secret key
